workflows:
  ios_release:
    name: Build iOS IPA (Release)
    environment:
      xcode: latest
    scripts:
      - name: Archive with Xcode
        script: |
          xcodebuild \
            -workspace MarketDataAnalyst.xcworkspace \
            -scheme MarketDataAnalyst \
            -configuration Release \
            -sdk iphoneos \
            archive \
            -archivePath "$CM_BUILD_DIR/MarketDataAnalyst.xcarchive"
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/MarketDataAnalyst.xcarchive" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$CM_BUILD_DIR/output"
    artifacts:
      - output/*.ipa
